window.AL_ADAMS_SITE = {
  identity: {
    name: "A. L. ADAMS",
    headline: "ART FROM THE BEAUTIFUL WRECKAGE",
    statement: "A. L. Adams makes art from fragments, stories, symbols, strange observations, and the things most people leave behind. The work moves between visual storytelling, altered objects, miniature worlds, paintings, found materials, and beautiful disorder."
  },
  links: {
    email: "inkandanarchy@gmail.com",
    shop: "",
    instagram: "",
    facebook: "",
    newsletter: ""
  },
  territories: [
    {
      name: "CHURCH OF SACRED DEBRIS",
      text: "Transformation, strange relics, discarded material, beautiful ruin, irreverence, survival, and meaning made from what remains."
    },
    {
      name: "INK AND ANARCHY",
      text: "Visual storytelling, independent creation, unruly ideas, writing, imagery, and work that refuses to behave politely merely because somebody designed a category for it."
    }
  ],
  artworks: [
    {
      id: "AL-01",
      image: "https://drive.google.com/thumbnail?id=1BqTMHi0u9C1PQLCJZxCul87tMTVpq58T&sz=w2400",
      title: "Kenny Leggins",
      category: "altered object",
      year: "",
      medium: "",
      dimensions: "",
      description: "",
      availability: "ask",
      price: "",
      shopUrl: "",
      alt: "Altered porcelain figurine with bright blue overalls, a small dog, and a hand-painted warning sign, photographed on paint cans in a workroom.",
      orientation: "portrait",
      note: "Started as a broken porcelain figurine recovered from a dumpster. Painted, altered, and given the wig."
    },
    {
      id: "AL-02",
      image: "https://drive.google.com/thumbnail?id=1Mczof1qGwmCV6Lg4CMbM_xDi73P_rQZE&sz=w2400",
      title: "Last Light Before Trouble",
      category: "painting",
      year: "",
      medium: "",
      dimensions: "",
      description: "",
      availability: "ask",
      price: "",
      shopUrl: "",
      alt: "Painting of a vivid sunset over water with mountains on the horizon and heavy clouds catching warm light.",
      orientation: "landscape",
      note: ""
    },
    {
      id: "AL-03",
      image: "https://drive.google.com/thumbnail?id=1BOSI9ZnC9NTPBKsd-8t_JAV994GGsKvz&sz=w2400",
      title: "Storm Coming",
      category: "painting",
      year: "",
      medium: "",
      dimensions: "",
      description: "",
      availability: "ask",
      price: "",
      shopUrl: "",
      alt: "Tiny hand-held landscape painting with a stormy blue-gray sky over a yellow field.",
      orientation: "portrait",
      note: ""
    },
    {
      id: "AL-04",
      image: "https://drive.google.com/thumbnail?id=1hKIgCAP3l8J0-Ow4mvVVXBP9J7FjoTTc&sz=w2400",
      title: "Open Late",
      category: "miniature",
      year: "",
      medium: "",
      dimensions: "",
      description: "",
      availability: "ask",
      price: "",
      shopUrl: "",
      alt: "Detailed miniature interior with a pastry counter, tiny tables and chairs, flowers, brick walls, and warm interior lighting.",
      orientation: "landscape",
      note: ""
    },
    {
      id: "AL-05",
      image: "https://drive.google.com/thumbnail?id=1P_w9SXYeHpoc1bQyJWKi1jrcbRi40X7w&sz=w2400",
      title: "Failure in the Moonlight",
      category: "painting",
      year: "",
      medium: "",
      dimensions: "",
      description: "",
      availability: "ask",
      price: "",
      shopUrl: "",
      alt: "Painting of a bright full moon breaking through dense gray clouds over a dark blue night sky.",
      orientation: "landscape",
      note: ""
    },
    {
      id: "AL-06",
      image: "https://drive.google.com/thumbnail?id=1uBEA9D3iGhRgLobVS9Iz_Oe9is7NQuAN&sz=w2400",
      title: "Surf the Rainbow",
      category: "painting",
      year: "",
      medium: "",
      dimensions: "",
      description: "",
      availability: "ask",
      price: "",
      shopUrl: "",
      alt: "Colorful painting of an ocean wave breaking beneath a purple, blue, orange, and green sky.",
      orientation: "square",
      note: ""
    },
    {
      id: "AL-07",
      image: "https://drive.google.com/thumbnail?id=1z-Xu6rtoDG-fp6XEFBQr_NhxiE5r0TgU&sz=w2400",
      title: "Mr. Noodle and Company",
      category: "sculpture",
      year: "",
      medium: "",
      dimensions: "",
      description: "",
      availability: "ask",
      price: "",
      shopUrl: "",
      alt: "Two handmade black cat figures with painted grins, bright eyes, and eccentric clothing, displayed in a workroom.",
      orientation: "portrait",
      note: ""
    },
    {
      id: "AL-08",
      image: "https://drive.google.com/thumbnail?id=1go0nso6406mK1H9RRdAm_Ezb6Z5-DuWf&sz=w2400",
      title: "Curious Collections of Crap",
      category: "assemblage",
      year: "",
      medium: "",
      dimensions: "",
      description: "",
      availability: "ask",
      price: "",
      shopUrl: "",
      alt: "Found-object arrangement laid out in a shallow white display, including small tools, bottle caps, keys, glass, wire, and miniature objects.",
      orientation: "landscape",
      note: ""
    },
    {
      id: "AL-09",
      image: "https://drive.google.com/thumbnail?id=1AX5zwssRRS2VviCWlVt1S3adWawQPSxh&sz=w2400",
      title: "Further Curious Collections of Crap",
      category: "assemblage",
      year: "",
      medium: "",
      dimensions: "",
      description: "",
      availability: "ask",
      price: "",
      shopUrl: "",
      alt: "Small open white box holding a spare arrangement of found objects including keys, candles, wire, metal pieces, glass, and paper.",
      orientation: "landscape",
      note: ""
    },
    {
      id: "AL-10",
      image: "https://drive.google.com/thumbnail?id=1MVYfUSBwwq63F_T507msrbixCF7K92Gj&sz=w2400",
      title: "Jar of Things That Seemed Important",
      category: "assemblage",
      year: "",
      medium: "",
      dimensions: "",
      description: "",
      availability: "ask",
      price: "",
      shopUrl: "",
      alt: "Glass jar assemblage containing small natural and found materials, photographed lying on its side.",
      orientation: "landscape",
      note: ""
    },
    {
      id: "AL-11",
      image: "https://drive.google.com/thumbnail?id=1dCue8CEddN06hsAsAx1pxIL3Oz1Ij8mX&sz=w2400",
      title: "Something Built a Nest Here",
      category: "assemblage",
      year: "",
      medium: "",
      dimensions: "",
      description: "",
      availability: "ask",
      price: "",
      shopUrl: "",
      alt: "Glass jar assemblage containing nest-like fibers, shells, a small red object, wood, and other collected materials.",
      orientation: "landscape",
      note: ""
    },
    {
      id: "AL-12",
      image: "https://drive.google.com/thumbnail?id=1ikV9KOvWvtLmp3BLw12jvq7d0DG4IOFI&sz=w2400",
      title: "The Department of Small Important Things",
      category: "assemblage",
      year: "",
      medium: "",
      dimensions: "",
      description: "",
      availability: "ask",
      price: "",
      shopUrl: "",
      alt: "Open metal case holding an orderly collection of small found objects, tools, printed pieces, beads, and miniature parts.",
      orientation: "landscape",
      note: ""
    }
  ]
};
