window.AL_ADAMS_SITE = {
  identity: {
    name: "A. L. ADAMS",
    headline: "ART FROM THE BEAUTIFUL WRECKAGE",
    statement: "A. L. Adams works across painting, altered objects, miniature worlds, found materials, digital images, visual storytelling, and narrative projects."
  },
  links: {
    email: "the.official.a.l.adams@gmail.com",
    shop: "https://payhip.com/ALAdamsStudio",
    instagram: "",
    facebook: "",
    newsletter: ""
  },
  territories: [
    {name:"CHURCH OF SACRED DEBRIS",text:"Found materials, altered objects, repair, transformation, and the material history already present in discarded things."},
    {name:"INK AND ANARCHY",text:"Writing, visual storytelling, independent publishing, and work that crosses literary and visual forms."},
    {name:"STUDIHELL 666",text:"Coloring books, printed matter, visual experiments, small objects, and limited-run studio work."},
    {name:"CANNED MEAT SHOW",text:"A graphic and performance project drawing on mid-century advertising, food packaging, cheap television, and commercial optimism."}
  ],
  artworks: [
    {id:"AL-01",image:"https://drive.google.com/thumbnail?id=1BqTMHi0u9C1PQLCJZxCul87tMTVpq58T&sz=w2400",title:"Kenny Leggins",category:"altered object",year:"",medium:"",dimensions:"",description:"",availability:"ask",price:"",shopUrl:"",alt:"Altered porcelain figurine with bright blue overalls, a small dog, and a hand-painted warning sign, photographed on paint cans in a workroom.",orientation:"portrait",note:"Started as a broken porcelain figurine recovered from a dumpster. Painted, altered, and given the wig."},
    {id:"AL-02",image:"https://drive.google.com/thumbnail?id=1Mczof1qGwmCV6Lg4CMbM_xDi73P_rQZE&sz=w2400",title:"Last Light Before Trouble",category:"painting",year:"",medium:"",dimensions:"",description:"",availability:"ask",price:"",shopUrl:"",alt:"Painting of a vivid sunset over water with mountains on the horizon and heavy clouds catching warm light.",orientation:"landscape",note:""},
    {id:"AL-03",image:"https://drive.google.com/thumbnail?id=1BOSI9ZnC9NTPBKsd-8t_JAV994GGsKvz&sz=w2400",title:"Storm Coming",category:"painting",year:"",medium:"",dimensions:"",description:"",availability:"ask",price:"",shopUrl:"",alt:"Tiny hand-held landscape painting with a stormy blue-gray sky over a yellow field.",orientation:"portrait",note:""},
    {id:"AL-04",image:"https://drive.google.com/thumbnail?id=1hKIgCAP3l8J0-Ow4mvVVXBP9J7FjoTTc&sz=w2400",title:"Open Late",category:"miniature",year:"",medium:"",dimensions:"",description:"",availability:"ask",price:"",shopUrl:"",alt:"Detailed miniature interior with a pastry counter, tiny tables and chairs, flowers, brick walls, and warm interior lighting.",orientation:"landscape",note:""},
    {id:"AL-05",image:"https://drive.google.com/thumbnail?id=1P_w9SXYeHpoc1bQyJWKi1jrcbRi40X7w&sz=w2400",title:"Failure in the Moonlight",category:"painting",year:"",medium:"",dimensions:"",description:"",availability:"ask",price:"",shopUrl:"",alt:"Painting of a bright full moon breaking through dense gray clouds over a dark blue night sky.",orientation:"landscape",note:""},
    {id:"AL-06",image:"https://drive.google.com/thumbnail?id=1uBEA9D3iGhRgLobVS9Iz_Oe9is7NQuAN&sz=w2400",title:"Surf the Rainbow",category:"painting",year:"",medium:"",dimensions:"",description:"",availability:"ask",price:"",shopUrl:"",alt:"Colorful painting of an ocean wave breaking beneath a purple, blue, orange, and green sky.",orientation:"square",note:""},
    {id:"AL-07",image:"https://drive.google.com/thumbnail?id=1z-Xu6rtoDG-fp6XEFBQr_NhxiE5r0TgU&sz=w2400",title:"Mr. Noodle and Company",category:"sculpture",year:"",medium:"",dimensions:"",description:"",availability:"ask",price:"",shopUrl:"",alt:"Two handmade black cat figures with painted grins, bright eyes, and eccentric clothing, displayed in a workroom.",orientation:"portrait",note:""},
    {id:"AL-08",image:"https://drive.google.com/thumbnail?id=1go0nso6406mK1H9RRdAm_Ezb6Z5-DuWf&sz=w2400",title:"Curious Collections of Crap",category:"assemblage",year:"",medium:"",dimensions:"",description:"",availability:"ask",price:"",shopUrl:"",alt:"Found-object arrangement laid out in a shallow white display, including small tools, bottle caps, keys, glass, wire, and miniature objects.",orientation:"landscape",note:""},
    {id:"AL-09",image:"https://drive.google.com/thumbnail?id=1AX5zwssRRS2VviCWlVt1S3adWawQPSxh&sz=w2400",title:"Further Curious Collections of Crap",category:"assemblage",year:"",medium:"",dimensions:"",description:"",availability:"ask",price:"",shopUrl:"",alt:"Small open white box holding a spare arrangement of found objects including keys, candles, wire, metal pieces, glass, and paper.",orientation:"landscape",note:""},
    {id:"AL-10",image:"https://drive.google.com/thumbnail?id=1MVYfUSBwwq63F_T507msrbixCF7K92Gj&sz=w2400",title:"Jar of Things That Seemed Important",category:"assemblage",year:"",medium:"",dimensions:"",description:"",availability:"ask",price:"",shopUrl:"",alt:"Glass jar assemblage containing small natural and found materials, photographed lying on its side.",orientation:"landscape",note:""},
    {id:"AL-11",image:"https://drive.google.com/thumbnail?id=1dCue8CEddN06hsAsAx1pxIL3Oz1Ij8mX&sz=w2400",title:"Something Built a Nest Here",category:"assemblage",year:"",medium:"",dimensions:"",description:"",availability:"ask",price:"",shopUrl:"",alt:"Glass jar assemblage containing nest-like fibers, shells, a small red object, wood, and other collected materials.",orientation:"landscape",note:""},
    {id:"AL-12",image:"https://drive.google.com/thumbnail?id=1ikV9KOvWvtLmp3BLw12jvq7d0DG4IOFI&sz=w2400",title:"The Department of Small Important Things",category:"assemblage",year:"",medium:"",dimensions:"",description:"",availability:"ask",price:"",shopUrl:"",alt:"Open metal case holding an orderly collection of small found objects, tools, printed pieces, beads, and miniature parts.",orientation:"landscape",note:""},
    {id:"AL-13",image:"assets/portfolio/holy-smokes.webp",title:"Holy Smokes",category:"assemblage",year:"2026",medium:"mixed media on miniature canvas",dimensions:"",description:"",availability:"archive",price:"",shopUrl:"",alt:"Small orange canvas with a winged cigarette beneath a fiber halo and the words Holy Smokes.",orientation:"portrait",note:"A tiny winged cigarette with a halo and a smoke problem.",featured:true},
    {id:"AL-14",image:"assets/portfolio/sibling-rivalry.svg",title:"Sibling Rivalry",category:"altered object",year:"2026",medium:"altered book / mixed media",dimensions:"",description:"",availability:"archive",price:"",shopUrl:"",alt:"Hand-held altered book spread with painted and collaged black shapes, tiny figures, and the words Sibling Rivalry.",orientation:"portrait",note:"Recent altered-book work.",featured:false},
    {id:"AL-15",image:"assets/portfolio/sheep-skeet.svg",title:"Sheep Skeet",category:"altered object",year:"2026",medium:"altered book / mixed media",dimensions:"",description:"",availability:"archive",price:"",shopUrl:"",alt:"Hand-held altered book spread with a checkerboard field, a sheep image, painted marks, and the words SHEEP SKEET.",orientation:"portrait",note:"Recent altered-book work.",featured:false},
    {id:"AL-16",image:"assets/portfolio/soft-girls-hit-hard.webp",title:"Soft Girls Hit Hard",category:"studio graphic",year:"2026",medium:"AI-assisted digital flash-sheet illustration",dimensions:"",description:"",availability:"archive",price:"",shopUrl:"",alt:"Aged-paper tattoo flash sheet with lipstick, high heels, brass knuckles, cherries, a cracked compact, and hand-lettered banners.",orientation:"portrait",note:"Lipstick, heels, brass knuckles, cherries, and the kind of advice nobody asked for.",featured:true},
    {id:"AL-17",image:"assets/portfolio/whatever-heart.webp",title:"Whatever — Heart Series, No. XIII",category:"studio graphic",year:"2026",medium:"AI-assisted digital illustration",dimensions:"",description:"",availability:"archive",price:"",shopUrl:"",alt:"Vintage-style illustration of a smoking cigarette in a cracked red heart above a wilted rose and a banner reading Whatever.",orientation:"portrait",note:"A cigarette buried in a cracked heart with a dying rose and the only useful response left."},
    {id:"AL-18",image:"assets/portfolio/ink-and-anarchy.webp",title:"The Wonderful Book of Ink and Anarchy!",category:"studio graphic",year:"2026",medium:"AI-assisted digital cover concept",dimensions:"",description:"",availability:"archive",price:"",shopUrl:"",alt:"Distressed Little Golden Book-style cover with an alien, a grinning black cat, flying chickens, books, a rainbow, and a rocket made from a fountain pen.",orientation:"square",note:"An alien, a grinning cat, several chickens, a flying pen, and the collapse of responsible children’s publishing."},
    {id:"AL-19",image:"assets/portfolio/bucket-pigeon.webp",title:"Untitled (Bucket Pigeon)",category:"studio graphic",year:"2026",medium:"AI-assisted digital illustration",dimensions:"",description:"",availability:"archive",price:"",shopUrl:"",alt:"Old-master-style portrait of a pigeon wearing a metal bucket and ragged cloth in a ruined alley, standing on discarded laundry.",orientation:"portrait",note:"A bucket-crowned pigeon presiding over laundry, crumbs, and the civic collapse behind it."},
    {id:"AL-20",image:"assets/portfolio/barter-king.webp",title:"Barter King",category:"studio graphic",year:"2026",medium:"AI-assisted digital illustration",dimensions:"",description:"",availability:"archive",price:"",shopUrl:"",alt:"Distressed old-master-style portrait of a large bird in a nest of french fries, wearing a paper Barter King crown above coins and dollar bills.",orientation:"portrait",note:"A fry-nesting bird with coins, bills, beads, and the ceremonial headwear of a fallen empire.",featured:true},
    {id:"AL-21",image:"assets/portfolio/french-fry-apocalypse.webp",title:"The French-Fry Apocalypse",category:"studio graphic",year:"2026",medium:"AI-assisted digital illustration",dimensions:"",description:"",availability:"archive",price:"",shopUrl:"",alt:"Distressed old-master-style scene of frantic seagulls attacking people in eighteenth-century clothing outside a MacDon’s restaurant over spilled french fries.",orientation:"portrait",note:"Eighteenth-century panic at the precise moment seagulls discover an unattended carton of fries."},
    {id:"AL-22",image:"assets/portfolio/dumpsterween.webp",title:"Dumpsterween",category:"studio graphic",year:"2026",medium:"AI-assisted digital illustration",dimensions:"",description:"",availability:"archive",price:"",shopUrl:"",alt:"Distressed storybook illustration of a crowned opossum eating ice cream atop discarded tubs while a small rat wears armor made from can tabs.",orientation:"portrait",note:"A paper-crowned opossum governing a kingdom of empty ice-cream tubs and aluminum-can regalia."},
    {id:"AL-23",image:"assets/portfolio/eye-moon.webp",title:"Eye Moon",category:"studio graphic",year:"2026",medium:"AI-assisted digital pattern study",dimensions:"",description:"",availability:"archive",price:"",shopUrl:"",alt:"Black ink-wash pattern with white crescent moons, watchful eyes, geometric symbols, stars, and occult-inspired linework.",orientation:"portrait",note:"A black-and-white field of moons, eyes, and small private cosmologies."},
    {id:"AL-24",image:"assets/portfolio/tasteful-meat.webp",title:"A Tasteful Meat",category:"studio graphic",year:"2026",medium:"AI-assisted digital pattern study",dimensions:"",description:"",availability:"archive",price:"",shopUrl:"",alt:"Cream-colored repeating pattern of canned meat, plated meat slices, parsley, lemon wedges, and the phrases A Tasteful Meat and So Good to Eat.",orientation:"portrait",note:"A repeating pattern of canned meat, parsley, lemon, and forced optimism."},
    {id:"AL-25",image:"assets/portfolio/canned-meat-show.webp",title:"Canned Meat Show",category:"studio graphic",year:"2026",medium:"AI-assisted digital poster design",dimensions:"",description:"",availability:"archive",price:"",shopUrl:"",alt:"Retro poster reading Canned Meat Show around an old television displaying a block of canned meat.",orientation:"portrait",note:"The title card for a program no network had the courage—or sodium allowance—to broadcast."},
    {id:"AL-26",image:"assets/portfolio/canned-meat-broadcast.webp",title:"Canned Meat Show: Broadcast Test",category:"studio graphic",year:"2026",medium:"AI-assisted digital illustration",dimensions:"",description:"",availability:"archive",price:"",shopUrl:"",alt:"Transparent-background retro television displaying a block of canned meat beside a Canned Meat Show title burst.",orientation:"portrait",note:"An old television displaying the show’s leading block of processed charisma."},
    {id:"AL-27",image:"assets/portfolio/eat-rice.webp",title:"Eat Rice So the Rich Can Have Potatoes",category:"studio graphic",year:"2026",medium:"AI-assisted digital propaganda poster",dimensions:"",description:"",availability:"archive",price:"",shopUrl:"",alt:"Vintage propaganda-style poster of a smiling family around a bowl of rice beneath the slogan Be Happy with Less—Eat Rice so the Rich can have Potatoes.",orientation:"portrait",note:"A cheerful family accepts austerity so the rich may continue hoarding potatoes."}
  ]
};
;(() => { const s=document.createElement("script"); s.src="reality.js"; document.head.appendChild(s); })();
